Do not include '../bits/..' system headers
tautschnig/cbmc pull request #2
Opened 2017-05-05 08:00 UTC by stahlbauer

2017-05-08 16:02 UTC, tautschnig requested changes
Some whitespace changes, please.

2017-05-08 16:02 UTC, tautschnig commented on src/goto-instrument/dump_c.cpp
> +      system_headers.insert(file_str.substr(std::string("/usr/include/").size()));
This line might be too long (80 chars max).

2017-05-08 16:02 UTC, tautschnig commented on src/goto-instrument/dump_c.cpp
> +    if (file_str.find("/bits/")==std::string::npos) {
Just style changes: No whitespace after `if`, and `{` should go on a new line.

2017-05-16 08:52 UTC, stahlbauer commented
The repository with the origin of pull request was broken. Closing this pull request and opening a new one.

2017-05-16 08:52 UTC, closed without merging